[tool.poetry]
name = "wordle_ql2581"
version = "0.1.0"
description = "A short description"
authors = ["Qinyang Lu"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
